### ISSUE TITLE
Where do I get the PIN for bot_authorise.py

### ISSUE THREAD

**Issue by rraallvv** [hugovk/twitter-tools#2]
I was immediately redirected to the callback URL and didn't saw the PIN anywhere in the temporary page that appeared before I was redirected. I was able to get some code in the URL parameter though,

```
https://example.com/?oauth_token=sometoken&oauth_verifier=somecode
```

I pasted the code from `oauth_verifier`in the URL into the commandline prompt and got this as a result

```
consumer_key: somecode
consumer_secret: somecode
access_token: somecode
access_token_secret: somecode
```

Not sure if that's what I was supposed to do

**Comment by hugovk** [comment]
Sorry, I only just saw this! Hope you got it sorted, please let me know if it's still an issue.
